default: &default
  database: <%= "estiu_#{Rails.env}" %>
  adapter: postgresql
  pool: 5 # fix?

development:
  <<: *default

test:
  <<: *default

rds: &rds
  host: <%= ENV['POSTGRESQL_HOST'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

staging:
  <<: *default
  <<: *rds
  
production:
  <<: *default
  <<: *rds
