default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: estiu_development

test:
  <<: *default
  database: estiu_test

production:
  <<: *default
  database: estiu_production
  host: <%= ENV['POSTGRESQL_HOST'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>