aws:
  region: <%= ENV['AWS_REGION'] %>
  receive_message: # See http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#receive_message-instance_method
    attribute_names:
      - All
concurrency: 4
delay: 0
queues:
  - [mailers, 1]
  - [default, 1]