#!/bin/sh

### BEGIN INIT INFO
# Provides:          unicorn
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the unicorn web server
# Description:       starts unicorn
### END INIT INFO

set -e # fail due to return codes
set -u # fail due to undefined variables

# PATH="/home/$USER/.rbenv/shims:/home/$USER/.rbenv/bin:$PATH" # potentially useful
# ENV="production"
USER="ubuntu"
TIMEOUT=60
APP_NAME="events"
APP_ROOT="/home/$USER/$APP_NAME"
PID_DIR=$APP_ROOT/tmp/pids
PID=$PID_DIR/unicorn.pid
CMD="cd $APP_ROOT;  bundle exec unicorn -D -c config/unicorn.rb" # dont pass -E $ENV , let's see if it works

# make sure the app exists
cd $APP_ROOT || exit 1

while [ ! -f .aws_init_complete ]
do
  sleep 1
done

sig () {
  test -s "$PID" && kill -$1 `cat $PID`
}

run () {
  su - $USER -c "$CMD"
}

case "$1" in
start)
  sig 0 && echo >&2 "Already running" && exit 0
  run
  ;;
stop)
  sig QUIT && exit 0
  echo >&2 "Not running"
  ;;
force-stop)
  sig TERM && exit 0
  echo >&2 "Not running"
  ;;
reopen-logs)
  sig USR1
  ;;
*)
  echo >&2 "Usage: $0 <start|stop|force-stop|reopen-logs>"
  exit 1
  ;;
esac